/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "2.0.21"
    id("net.neoforged.gradle.userdev") version "7.0.120"
    kotlin("plugin.serialization") version "1.9.23" 
}

group = "com.example.logicchisel"
version = "1.0.0"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

repositories {
    mavenCentral()
    maven(url = "https://maven.neoforged.net/releases/")
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation("net.neoforged:neoforge:1.21.5-21.5.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.6.3")
    implementation("io.kamel:kamel-yaml:0.5.0")
}

// NeoForge用のrunタスク例
// tasks.register<JavaExec>("runClient") {
//     group = "application"
//     mainClass.set("net.neoforged.fml.loading.FMLClientLaunchProvider")
//     classpath = sourceSets["main"].runtimeClasspath
//     args = listOf("--username", "Dev")
// }
